[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.140"
simple_logger = "5.0.0"
log = { version = "^0.4.14", features = ["std"] }
tempfile = "3.19.1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11.3", features = ["stream"] }
futures-util = "0.3.31"
indicatif = "0.17.11"
anyhow = "1.0"
