name: WarpFox Runtime Release

on:
  workflow_dispatch:
  workflow_call:

jobs:
  debug-inputs:
    name: Debug inputs
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}"
          echo "GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}"
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"

  build-source:
    permissions: write-all
    name: Build Source
    runs-on: ubuntu-latest
    environment:
      name: Deploy-Runtime
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get and export firefox version
        id: get-firefox-version
        run: |
          echo "Getting Firefox version"
          FIREFOX_VERSION=$(curl -s https://product-details.mozilla.org/1.0/firefox_versions.json | jq -r '.FIREFOX_NIGHTLY')
          echo "FIREFOX_VERSION=$FIREFOX_VERSION" >> $GITHUB_ENV
          echo "FIREFOX_VERSION=$FIREFOX_VERSION"

      - name: Install dependencies
        run: |
          sh ./packages/runtime/build/install-deps.sh

      - name: Build
        run: |
          cd packages/runtime
          cargo run

      - name: Move engine directory
        run: |
          mv packages/runtime/engine/ ./firefox-source

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: firefox-v${{ needs.get-firefox-version.outputs.FIREFOX_VERSION }}
          prerelease: false
          fail_on_unmatched_files: false
          generate_release_notes: false
          name: "Release build - firefox v${{ needs.get-firefox-version.outputs.FIREFOX_VERSION }}"
          files: |
            firefox-source
